### ISSUE TITLE
Add "event.register"

### ISSUE THREAD

**Issue by MaxymVlasov** [itkpi/itkpimail#10]
1. Install it on http://it.kpi.pp.ua/admin/events/template/6/  between "event.place" and "event.image_url" 
2. Add it to  WYSIWYG

**Comment by rrader** [comment]
Should it be just one line field or multi-line WYSIWYG editor?

**Comment by MaxymVlasov** [comment]
One line 
Text replacement of register link -  "Реєстрація"
